on:
  push:
    tags:
      - v*

env:
  NODE_VERSION: 24.16.0
  PROJECT_ID: darci-gg

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install PNPM
        uses: pnpm/action-setup@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Create .env file
        run: |
          echo '${{ secrets.ENV_FILE_PROD }}' > .env
          echo "COMMIT_HASH=${GITHUB_SHA:0:4}" >> .env
      - name: Build
        run: pnpm build
      - name: Prepare authorization with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_PROD }}
      - name: Deploy to production environment
        run: pnpx firebase-tools deploy --only=hosting --project="$PROJECT_ID"
